version: '3.8'
services:
  fastapp:
    build: .
    ports:
      - "5000:5000"
    command: >
      sh -c "alembic upgrade head && 
             uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Optional: ensures logs are output in real-time




























# env_file:
      #     - .env
      # environment:
      #     - PYTHONPATH=/app
      #     - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      #     - DB_NAME=${DB_NAME}
      #     - DB_USER=${DB_USER}
      #     - DB_PASSWORD=${DB_PASSWORD}
      #     - DB_HOST=${DB_HOST}
      #     - DB_PORT=${DB_PORT}
     

  #   db:
  #     image: postgres:17
  #     restart: always
  #     environment:
  #       - "POSTGRES_HOST_AUTH_METHOD=trust"
  #       - POSTGRES_DB=${DB_NAME}
  #       - POSTGRES_USER=${DB_USER}
  #       - POSTGRES_PASSWORD=${DB_PASSWORD}
    
  #     volumes:
  #       - ../mydb:/var/lib/postgresql/data
      
  #     ports:
  #       - "5433:5432" 
  #     env_file:
  #       - .env
  #     expose: 
  #       - 5433

  # volumes:
  #   postgres_data: {}

