"""ff

Revision ID: 05db81f61f5c
Revises: 5d2e399e5b2b
Create Date: 2024-12-16 11:19:23.972030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05db81f61f5c'
down_revision: Union[str, None] = '5d2e399e5b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipients', 'signed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('signed_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
