"""firts migrations

Revision ID: 0d4be715a040
Revises: 82e42431fd10
Create Date: 2024-12-06 16:35:18.241002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4be715a040'
down_revision: Union[str, None] = '82e42431fd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('fieldtype', sa.Column('inserted', sa.Boolean(), nullable=False))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('fieldtype', 'inserted')
#     # ### end Alembic commands ###


def upgrade() -> None:
    # Add a boolean column with a default value of False
    op.add_column(
        'fieldtype',
        sa.Column(
            'inserted', 
            sa.Boolean(), 
            nullable=False, 
            server_default=sa.text('0')  # Use 0 as False in SQLite
        )
    )


def downgrade() -> None:
    # Drop the column if downgrading
    op.drop_column('fieldtype', 'inserted')