"""new migration apply

Revision ID: 21cf863119d2
Revises: 871a3402cb12
Create Date: 2024-12-24 09:21:29.594422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cf863119d2'
down_revision: Union[str, None] = '871a3402cb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('inserted', sa.Boolean(), nullable=True))
    op.drop_column('documnet_field', 'sign_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('sign_status', sa.BOOLEAN(), nullable=True))
    op.drop_column('documnet_field', 'inserted')
    # ### end Alembic commands ###
