"""remove fields


Revision ID: 29831e1b6d53
Revises: 386da711a106
Create Date: 2024-12-10 13:53:21.352347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29831e1b6d53'
down_revision: Union[str, None] = '386da711a106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fieldtype', 'positionX')
    op.drop_column('fieldtype', 'width')
    op.drop_column('fieldtype', 'height')
    op.drop_column('fieldtype', 'positionY')
    op.drop_column('fieldtype', 'signature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fieldtype', sa.Column('signature', sa.VARCHAR(), nullable=True))
    op.add_column('fieldtype', sa.Column('positionY', sa.VARCHAR(), nullable=True))
    op.add_column('fieldtype', sa.Column('height', sa.VARCHAR(), nullable=True))
    op.add_column('fieldtype', sa.Column('width', sa.VARCHAR(), nullable=True))
    op.add_column('fieldtype', sa.Column('positionX', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
