"""remove true

Revision ID: 5d2e399e5b2b
Revises: 7b9aad396dfe
Create Date: 2024-12-16 10:30:53.304532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e399e5b2b'
down_revision: Union[str, None] = '7b9aad396dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'inserted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('inserted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
