"""new migration apply

Revision ID: 871a3402cb12
Revises: a62985eae1e3
Create Date: 2024-12-24 09:18:54.400074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871a3402cb12'
down_revision: Union[str, None] = 'a62985eae1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('note', sa.String(), nullable=True))
    op.add_column('documnet_field', sa.Column('sign_status', sa.Boolean(), nullable=True))
    op.add_column('documnet_field', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('documnet_field', sa.Column('signing_order', sa.Enum('PARALLEL', 'VIEWER', name='signingorder'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'signing_order')
    op.drop_column('documnet_field', 'is_current')
    op.drop_column('documnet_field', 'sign_status')
    op.drop_column('documents', 'note')
    # ### end Alembic commands ###
