"""chage default

Revision ID: 8cc70e94de7a
Revises: 271e54227751
Create Date: 2024-12-05 16:08:24.292675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc70e94de7a'
down_revision: Union[str, None] = '271e54227751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipient', 'created_at')
    # ### end Alembic commands ###
