"""add fieldstype

Revision ID: b212aad12080
Revises: f085b0ef1928
Create Date: 2024-12-05 13:58:20.913133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b212aad12080'
down_revision: Union[str, None] = 'f085b0ef1928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FieldType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FieldType_id'), 'FieldType', ['id'], unique=False)
    op.create_index(op.f('ix_FieldType_name'), 'FieldType', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_FieldType_name'), table_name='FieldType')
    op.drop_index(op.f('ix_FieldType_id'), table_name='FieldType')
    op.drop_table('FieldType')
    # ### end Alembic commands ###
