"""new migration apply

Revision ID: b8d1525b7813
Revises: 9ec76415196d
Create Date: 2024-12-24 12:58:07.255709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d1525b7813'
down_revision: Union[str, None] = '9ec76415196d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'order')
    # ### end Alembic commands ###
