"""new migration apply

Revision ID: befe2ba050bf
Revises: 21cf863119d2
Create Date: 2024-12-24 09:58:19.650648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befe2ba050bf'
down_revision: Union[str, None] = '21cf863119d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('signed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'signed_at')
    # ### end Alembic commands ###
