"""new migration apply

Revision ID: c2e696366e13
Revises: dad00fa7f0b7
Create Date: 2024-12-24 12:24:27.551256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e696366e13'
down_revision: Union[str, None] = 'dad00fa7f0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('signing_order', sa.Enum('PARALLEL', 'VIEWER', name='signingorder'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'signing_order')
    # ### end Alembic commands ###
