"""new migration apply

Revision ID: dad00fa7f0b7
Revises: befe2ba050bf
Create Date: 2024-12-24 10:36:31.423897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad00fa7f0b7'
down_revision: Union[str, None] = 'befe2ba050bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'signing_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('signing_order', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
