"""firts migrations

Revision ID: e7766ecd26fe
Revises: 0d4be715a040
Create Date: 2024-12-06 16:44:45.702296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7766ecd26fe'
down_revision: Union[str, None] = '0d4be715a040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'inserted')
    op.alter_column('fieldtype', 'inserted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fieldtype', 'inserted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('documnet_field', sa.Column('inserted', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
