"""new migration apply

Revision ID: e8e31678e9eb
Revises: b8d1525b7813
Create Date: 2024-12-24 13:11:27.906874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e31678e9eb'
down_revision: Union[str, None] = 'b8d1525b7813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documnet_field', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documnet_field', 'order')
    # ### end Alembic commands ###
