"""add doc status

Revision ID: f085b0ef1928
Revises: 4c9fce69cfae
Create Date: 2024-12-05 12:17:18.244036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f085b0ef1928'
down_revision: Union[str, None] = '4c9fce69cfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.Enum('SIGNED', 'PENDING', 'COMPLETED', 'DRAFT', name='documentstatus'), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE documents SET status = 'DRAFT' WHERE status IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
